version: '3'
services:
  fhir-server-dev:
      # Note that the path of the Dockerfile and context is relative to the *primary*
      # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
      # array). The sample below assumes your primary file is in the root of your project.
      build:
        context: .
        dockerfile: ./Dockerfile
        args:
          VARIANT: 3.1
          INSTALL_NODE: "false"
          NODE_VERSION: lts/*
          INSTALL_AZURE_CLI: "false"
      volumes:
        - ..:/workspace:cached
      command: /bin/sh -c "while sleep 1000; do :; done"
      depends_on:
        - sql
      ports:     
      - "44348:44348"
  sql:
      image: "mcr.microsoft.com/mssql/server"
      environment:
        SA_PASSWORD: ${SAPASSWORD}
        ACCEPT_EULA: Y
      healthcheck:
          test: ["CMD", "/opt/mssql-tools/bin/sqlcmd","-U sa -P ${SAPASSWORD} -Q 'SELECT * FROM INFORMATION_SCHEMA.TABLES'"]
          interval: 10s
          timeout: 10s
          retries: 6